### ISSUE TITLE
Dependency issues when installing check50 on Ubuntu 14.04

### ISSUE THREAD

**Issue by EliasJorgensen** [tysonchamp/cs50#2]
Render50 and Style50 now installs, but when Check50 installs, it prints an error message about missing dependencies and that they won't get installed.
I've uploaded the terminal log to pastebin, so you can see it for your self.
http://pastebin.com/PWmEQtw2

**Comment by tysonchamp** [comment]
first run 
sudo apt-get install nodejs -y
then
sudo apt-get -f install

let me know if it solve your problem. Hope it will. Are you running 64bit? if yes then follow the instruction on readme file (recently updated).

**Comment by EliasJorgensen** [comment]
I managed to get it installed using the source for check50 available on GitHub.
I used the script on a completely clean install of Ubuntu, so there's probably a few changes that needs to be made to it.
And yeah, i'm using the 64bit version ;)

**Comment by tysonchamp** [comment]
Thanks for your replay. actually the script is only for 32bit
