### ISSUE TITLE
Include Stanford Portable Library

### ISSUE THREAD

**Issue by pierrebeaucamp** [tysonchamp/cs50#4]
pset3 and pset4 of CS50 need the [Stanford Portable Library](https://github.com/cs50/spl) installed.

**Comment by tysonchamp** [comment]
I included the SPL. Please do check and let me know if any error occur

**Comment by pierrebeaucamp** [comment]
lgtm

Once [my PRs](https://github.com/cs50/spl/pulls) are merged into [cs50/spl](https://github.com/cs50/spl), I would maybe change the script to pull SPL from there. But that's just a minor nitpick for now.
